// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatroom.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ChatRequest 请求结构
type ChatRequest struct {
	Roomid               string   `protobuf:"bytes,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Userid               string   `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatRequest) Reset()         { *m = ChatRequest{} }
func (m *ChatRequest) String() string { return proto.CompactTextString(m) }
func (*ChatRequest) ProtoMessage()    {}
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatroom_87cea8ae28164a32, []int{0}
}
func (m *ChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatRequest.Unmarshal(m, b)
}
func (m *ChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatRequest.Marshal(b, m, deterministic)
}
func (dst *ChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatRequest.Merge(dst, src)
}
func (m *ChatRequest) XXX_Size() int {
	return xxx_messageInfo_ChatRequest.Size(m)
}
func (m *ChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChatRequest proto.InternalMessageInfo

func (m *ChatRequest) GetRoomid() string {
	if m != nil {
		return m.Roomid
	}
	return ""
}

func (m *ChatRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *ChatRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// ChatResponse 响应结构
type ChatResponse struct {
	Roomid               string   `protobuf:"bytes,1,opt,name=roomid,proto3" json:"roomid,omitempty"`
	Userid               string   `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatResponse) Reset()         { *m = ChatResponse{} }
func (m *ChatResponse) String() string { return proto.CompactTextString(m) }
func (*ChatResponse) ProtoMessage()    {}
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chatroom_87cea8ae28164a32, []int{1}
}
func (m *ChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatResponse.Unmarshal(m, b)
}
func (m *ChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatResponse.Marshal(b, m, deterministic)
}
func (dst *ChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatResponse.Merge(dst, src)
}
func (m *ChatResponse) XXX_Size() int {
	return xxx_messageInfo_ChatResponse.Size(m)
}
func (m *ChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChatResponse proto.InternalMessageInfo

func (m *ChatResponse) GetRoomid() string {
	if m != nil {
		return m.Roomid
	}
	return ""
}

func (m *ChatResponse) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *ChatResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatRequest)(nil), "pb.ChatRequest")
	proto.RegisterType((*ChatResponse)(nil), "pb.ChatResponse")
}

func init() { proto.RegisterFile("chatroom.proto", fileDescriptor_chatroom_87cea8ae28164a32) }

var fileDescriptor_chatroom_87cea8ae28164a32 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0x48, 0x2c,
	0x29, 0xca, 0xcf, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x0a,
	0xe7, 0xe2, 0x76, 0xce, 0x48, 0x2c, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe3,
	0x62, 0x03, 0x29, 0xc8, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x40, 0xe2,
	0xa5, 0xc5, 0xa9, 0x45, 0x99, 0x29, 0x12, 0x4c, 0x10, 0x71, 0x08, 0x4f, 0x48, 0x82, 0x8b, 0x3d,
	0x37, 0xb5, 0xb8, 0x38, 0x31, 0x3d, 0x55, 0x82, 0x19, 0x2c, 0x01, 0xe3, 0x2a, 0x45, 0x70, 0xf1,
	0x40, 0x0c, 0x2e, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xa5, 0x9e, 0xc9, 0x46, 0x66, 0x5c, 0x2c, 0x20,
	0x93, 0x85, 0xf4, 0xb8, 0xd8, 0x83, 0x13, 0x2b, 0xc1, 0x4c, 0x7e, 0xbd, 0x82, 0x24, 0x3d, 0x24,
	0x7f, 0x48, 0x09, 0x20, 0x04, 0x20, 0xf6, 0x2b, 0x31, 0x38, 0xb1, 0x44, 0x31, 0x15, 0x24, 0x25,
	0xb1, 0x81, 0xfd, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xfa, 0xdd, 0xb0, 0x0d, 0x01,
	0x00, 0x00,
}
